[build]
  builder = "DOCKERFILE"
  dockerfilePath = "server/Dockerfile"

[deploy]
  startCommand = "node index.js"
  healthcheckPath = "/"
  healthcheckTimeout = 30
  restartPolicyType = "on_failure"
